### ISSUE TITLE
configuration file missing

### ISSUE THREAD

**Issue by seanmacavaney** [gzerveas/CODER#1]
Hi, thanks for the great work!

Looks like the following configuration files are missing from the repository: `coder_tasb_train_config.json`, `coder_tasb_eval_config.json`

Thanks!

**Comment by gzerveas** [comment]
Hi Sean,

Oh, it looks like I forgot to simplify the names of the original config files to match the simple names of the README. So the files in `configurations` are correct, but `NoDecoder_Qenc_tasb_aggFirst_tasb1000_Rneg0_ListnetLoss_ROPloss_valTASB_Axm_2021-11-12_16-42-08_IZc_configuration.json` is supposed to be used for training, and `TEST_2020test_NoDecoder_Qenc_tasb_aggFirst_tasb1000_Rneg0_ListnetLoss_ROPloss_valTASB_configuration.json` for evaluation.

**Comment by seanmacavaney** [comment]
Ah, gotcha. Thanks!
